### ISSUE TITLE
v2.17.0 introduces a regression

### ISSUE THREAD

**Issue by rpadovani** [mafintosh/is-my-json-valid#149] opened 2017-12-18 12:05 UTC
I do not use this package directly, but xo does. 

After you released 2.17.0 xo doesn't run anymore with this error:

If you break retro-compatibility, you are supposed to to a major version bump.  

```
/builds/***/node_modules/is-my-json-valid/index.js:366
      visit(name+'['+i+']', node.items, reporter, filter, schemaPath.concat('items'))
                                                                     ^

TypeError: Cannot read property 'concat' of undefined
    at visit (/builds/***/node_modules/is-my-json-valid/index.js:366:70)
    at /build/***/node_modules/is-my-json-valid/index.js:416:9
    at Array.forEach (<anonymous>)
    at visit (/builds/***/node_modules/is-my-json-valid/index.js:409:18)
    at /builds/***/node_modules/is-my-json-valid/index.js:543:9
    at Array.forEach (<anonymous>)
    at visit (/builds/***/node_modules/is-my-json-valid/index.js:540:31)
    at compile (/builds/***/node_modules/is-my-json-valid/index.js:565:3)
    at visit (/builds/***/node_modules/is-my-json-valid/index.js:340:16)
    at /builds/***/node_modules/is-my-json-valid/index.js:416:9

**Comment by ambewas** [comment] 2017-12-18 12:11
same problem here, and can't fix a version in our package.json due to it being a deeper dependency as well.

**Comment by hustcc** [comment] 2017-12-18 12:13
```
/Users/xxx/Documents/git/d-vision/.eslintrc:
	Configuration for rule "no-use-before-define" is invalid:
Cannot read property 'concat' of undefined
```

Similar error.

**Comment by shuky19** [comment] 2017-12-18 12:14
Same here, using eslint...

**Comment by somprabhsharma** [comment] 2017-12-18 12:15
Similar error.

**Comment by Ysudo** [comment] 2017-12-18 12:18
same problem here.

**Comment by vaail** [comment] 2017-12-18 12:18
same problem here

**Comment by xiaoyang4011** [comment] 2017-12-18 12:20
same problem here

**Comment by GottfridL** [comment] 2017-12-18 12:21
same problem here!

**Comment by mateussmohamed** [comment] 2017-12-18 12:24
same problem here!

**Comment by sebheitzmann** [comment] 2017-12-18 12:28
+1

**Comment by Clement-TS** [comment] 2017-12-18 12:30
Same here with [standardjs](https://github.com/standard/standard)

**Comment by jasollien** [comment] 2017-12-18 12:34
Same here

**Comment by SonoAlien** [comment] 2017-12-18 12:35
+1

**Comment by Ricardowouda** [comment] 2017-12-18 12:35
Same problem here.

**Comment by Andrei997** [comment] 2017-12-18 12:36
Same here with Nuxt.

**Comment by vaail** [comment] 2017-12-18 12:45
@mafintosh @LinusU @deBhal https://github.com/mafintosh/is-my-json-valid/pull/150

**Comment by netdeamon** [comment] 2017-12-18 12:49
Same issue here

**Comment by l86110** [comment] 2017-12-18 12:50
Same here

**Comment by ameya-kulkarni** [comment] 2017-12-18 12:51
Same here

**Comment by spotscale** [comment] 2017-12-18 12:55
Same issue here.

**Comment by kalanda** [comment] 2017-12-18 12:55
Same here

**Comment by vzorge** [comment] 2017-12-18 12:57
Same here.

**Comment by joachimhb** [comment] 2017-12-18 12:58
Same here

**Comment by shahsank3t** [comment] 2017-12-18 13:00
Same here.

**Comment by dindonus** [comment] 2017-12-18 13:02
Same here

**Comment by louischan-oursky** [comment] 2017-12-18 13:05
Same here

**Comment by satishwaghela** [comment] 2017-12-18 13:06
Same here

**Comment by sameer79** [comment] 2017-12-18 13:06
Same here

**Comment by EreMaijala** [comment] 2017-12-18 13:09
I believe it's already obvious this is a major issue, so I'd like to suggest everyone to just subscribe on this issue instead of adding more "Same here" comments.

**Comment by voxpelli** [comment] 2017-12-18 13:10
Fixed by #151 and released as `2.17.1` – thanks @LinusU for quick fix! 👍

**Comment by LinusU** [comment] 2017-12-18 13:10
Fix published as `2.17.1`, so sorry for any inconvenience caused!

**Closed by LinusU** 2017-12-18 13:10 UTC

**Comment by LinusU** [comment] 2017-12-18 13:13
Super sorry for this 🙈 

Will try to add more test coverage and possibly move to TypeScript to prevent this from happening again 👌

**Comment by LinusU** [comment] 2017-12-18 13:16
@akryvda, it's already published: `2.17.1`

**Comment by akryvda** [comment] 2017-12-18 13:17
Thanks, for quick update! Will rerun our pipelines

**Comment by peterclifflm** [comment] 2017-12-18 13:18
My build was failing but now is not. Fast work - thank you!

**Comment by LinusU** [comment] 2017-12-18 13:20
`2.17.0` have been deprecated on npm with the following message:

> A bug in this version causes an exception to be thrown when using anyOf or oneOf, please upgrade to 2.17.1 instead

**Comment by rpadovani** [comment] 2017-12-18 13:30
Thanks for your fast fix on this!

**Comment by LinusU** [comment] 2017-12-18 13:54
Would like to take this opportunity to plug lock files 🔒📝 

By using npm 5 or newer, or [yarn](https://yarnpkg.com/), a `package-lock.json` (or `yarn.lock`) file will automatically be created when adding or removing dependencies. This file will contain the exact version of every dependency (even the dependency of your dependencies, and so forth). Whenever `npm install` (or `yarn`) is run, it will look for this file and install the exact dependencies as the last time, thus ensuring that your builds are reproducible.

The file should be commited together with the rest of the code, so that everyone that works on the project have the same versions of every dependency, and so that the CI and deploy also uses the same versions.

More reading: ["Yarn determinism" blog post](https://yarnpkg.com/blog/2017/05/31/determinism/), [package-lock.json on npm docs](https://docs.npmjs.com/files/package-lock.json), [yarn.lock on yarn docs](https://yarnpkg.com/lang/en/docs/yarn-lock/)

Again, sorry for any inconvenience, hopefully this wont happen again, but I would advice everyone to start using lock files to minimize the impact if (when 😄) it happens the next time. If anyone is in London I'd be happy to buy you a beer!

Cheers 🍻

**Comment by deBhal** [comment] 2017-12-19 02:14
I'd also like to add my apologies to everyone inconvenienced, and my thanks to @LinusU and @shalevshalit  @juliangruber @shalevshalit who all provided fixes so quickly while I was asleep.

> Will try to add more test coverage

We did have tests here that seemed solid so I've opened a PR here to cover this specific case but that didn't really seem adequate so I've also opened a PR to beef up the upstream json-schema-org repo as well (https://github.com/json-schema-org/JSON-Schema-Test-Suite/pull/211)
