### ISSUE TITLE
Loading a schema in is-my-json-valid has side effects

### ISSUE THREAD

**Issue by Muscula** [mafintosh/is-my-json-valid#9] opened 2015-01-29 13:14 UTC
The schema:
```js
{
                "items": [
                        {}
                ],
                "additionalItems": {
                        "type": "integer"
                }
}
```
gets turned into
```js
 {
                "items": [
                        {}
                ],
                "additionalItems": {
                        "type": "integer"
                },
                "properties": {
                        "0": {}
                },
                "type": "array",
                "tuple": true
}
```
I don't think loading a schema should have side-effects on the original schema.

**Comment by mafintosh** [comment] 2015-01-29 13:30
Fixed in 2.2.1

**Closed by mafintosh** 2015-01-29 13:30 UTC

**Comment by Muscula** [comment] 2015-01-29 13:48
Also in this official test:
````
{
        "description": "invalid type for default",
        "schema": {
                "properties": {
                        "foo": {
                                "type": "integer",
                                "default": []
                        }
                }
        },
        "tests": [
                {
                        "description": "valid when property is specified",
                        "data": {
                                "foo": 13
                        },
                        "valid": true
                },
                {
                        "description": "still valid when the invalid default is used",
                        "data": {
                                "foo": []
                        },
                        "valid": true
                }
        ]
}
```
I found that is-my-json-valid actually modifies the date in the last test, removing the foo property:
```js
{
        "description": "invalid type for default",
        "schema": {
                "properties": {
                        "foo": {
                                "type": "integer",
                                "default": []
                        }
                }
        },
        "tests": [
                {
                        "description": "valid when property is specified",
                        "data": {
                                "foo": 13
                        },
                        "valid": true
                },
                {
                        "description": "still valid when the invalid default is used",
                        "data": {}, //foo missing here after validating with is-my-json-valid
                        "valid": true
                }
        ]
}
```

**Comment by mafintosh** [comment] 2015-01-29 14:02
Can't reproduce this. Can you provide a concrete runnable example?

**Comment by mafintosh** [comment] 2015-01-29 14:03
Using 2.2.1 :)

**Comment by Muscula** [comment] 2015-01-29 14:09
I'm using 2.2.1 :-) and it's happening here in my testsuite:
https://github.com/Muscula/json-schema-benchmark/blob/master/testRunner.js#L85

It's only happening for two tests in the official testsuite:
```
is-my-json-valid had a side-effect on (altered the original) the schema (or data) in the test "invalid type for default, still valid when the invalid default is used"

is-my-json-valid had a side-effect on (altered the original) the schema (or data) in the test "invalid string value for default, still valid when the invalid default is used"
```
This was also how I caught the first initial side-effect on the schema that you just fixed.

Other validators run through without any side-effects. For example `themis` and `jjv`

**Comment by Muscula** [comment] 2015-01-29 14:13
It should happen when you use this schema:
```js
{
                "properties": {
                        "foo": {
                                "type": "integer",
                                "default": []
                        }
                }
}
```
To validate this data:
```js
{
                                "foo": []
}
```

**Comment by Muscula** [comment] 2015-01-29 14:19
I'm having a hard time reproducing it too... hmm

**Comment by mafintosh** [comment] 2015-01-29 14:20
``` js
var validator = require('is-my-json-valid')
var valid = validator({
  "properties": {
    "foo": {
      "type": "integer",
      "default": []
    }
  }
})

var data = {foo: []}

console.log('data before', data)
console.log('valid:', valid(data))
console.log('data now:', data)
```

produces

```
data before { foo: [] }
valid: false
data now: { foo: [] }
```

**Comment by Muscula** [comment] 2015-01-29 14:29
It's the other way around, foo is inserted in an empty document: (sorry got that wrong)
```js
var schema = {
	"properties": {
		"foo": {
			"type": "integer",
			"default": []
		}
	}
};
var data = {};
require('is-my-json-valid')(schema)(data);
console.log(data);
// { foo: [] }
```

**Comment by mafintosh** [comment] 2015-01-29 14:56
Working as intended. This is how the `default` property works in JSON schema (which is super weird)

**Comment by mafintosh** [comment] 2015-01-29 15:01
Hmm, http://json-schema.org/latest/json-schema-validation.html#anchor101 sounds like different though

**Comment by mafintosh** [comment] 2015-01-29 15:06
After re-reading the above section and discussing this with @watson it no longer sets default values. I really disliked that behavior anyways. Also the json schema test suite still passes.

Released in 2.3.0

**Comment by Muscula** [comment] 2015-01-29 15:13
OK, so you are overriding the spec? Doing the sensible thing instead?

**Comment by mafintosh** [comment] 2015-01-29 15:17
No I'm still spec compliant :) (see the above link). I originally misunderstood what default should do.

**Comment by watson** [comment] 2015-01-29 15:46
@Muscula as far as I read the specs `default` is only meant as metadata and shouldn't affect the outcome of the validation. I.e. if `default` is the integer 1 but the type is a string, it should still validate. So `default` is in a way just like `name` and `description`
